vich_uploader:
    db_driver: orm

    mappings:
        sign:
            uri_prefix: /images/sign
            upload_destination: '%kernel.project_dir%/public/images/sign'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer